cache: bundler
sudo: false
language: ruby

matrix:
  include:
    - rvm: 2.4.9
      env: "CHECK=rubocop"

    - rvm: 2.4.9
      env: "CHECK=test"

    - rvm: 2.5.7
      env: "CHECK=test"

    - rvm: jruby-9.2.9.0
      env: "CHECK=test"

    - rvm: 2.4.9
      env: "CHECK=rubocop"

install:
  - gem update --system
  - gem install bundler
  - bundle --version
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
script:
  - "bundle exec rake $CHECK"
